import '../../../models/project.dart';
import '../../authoring.dart';

final Buffer page = makePage(
  'xyno-scholar/lib/models/notebook_entry.dart',
  lines: [
    cm('//', '──────────────────────────────────────────'),
    cm('//', 'notebook_entry.dart — a topic worth keeping, with the student’s own words'),
    cm('//', 'the only model written to disk'),
    cm('//', '──────────────────────────────────────────'),
    blank,
    kv('role', 'a narrow topic saved to the persistent notebook, with personal notes'),
    kv('language', 'Dart'),
    kv('size', '43 lines'),
    kv('history', 'one commit, 7a200e7 (2026-08-06); unchanged since'),
    kv('stored under', 'shared_preferences key xyno_scholar_notebook_v1 (a JSON list)'),
    ...sec('why this file exists'),
    ...para('//',
        'Everything else the model produces is disposable: generate '
        'again and it is replaced. A narrow topic, though, may be the '
        'first draft of a mémoire, and a language model will not give '
        'the same answer twice, so the only way to keep a topic is to '
        'keep the object. The notebook is that. A NotebookEntry wraps '
        'a NarrowTopic with three pieces of metadata that the topic '
        'itself does not have.'),
    ...code('dart', 'lib/models/notebook_entry.dart · the fields', r'''
/// A narrow topic saved to the persistent notebook, with the user's own notes.
class NotebookEntry {
  final String id;
  final NarrowTopic topic;
  final String personalNotes;
  final DateTime savedAt;'''),
    ...pt('//', 'id',
        'a uuid generated by the notebook provider at save time. It is '
        'what remove and updateNotes look entries up by.'),
    ...pt('//', 'personalNotes',
        'the student’s text, empty at save time.'),
    ...pt('//', 'savedAt',
        'when it was saved. Stored and parsed, but displayed nowhere: '
        'the drawer shows title, pitch and notes only.'),

    ...sec('why the entry has its own id'),
    ...para('//',
        'NarrowTopic has an id field too, but it is chosen by the '
        'model and ignored by the app (see narrow_topic.dart). Using it '
        'would make saving the same topic twice collide, and would put '
        'a model-controlled string in a role where uniqueness matters. '
        'The notebook gives each save its own identity instead:'),
    ...code('dart', 'lib/providers/notebook_provider.dart · save', r'''
  Future<void> save(NarrowTopic topic) async {
    final current = state.value ?? [];
    final entry = NotebookEntry(
      id: _uuid.v4(),
      topic: topic,
      personalNotes: '',
      savedAt: DateTime.now(),
    );
    final updated = [entry, ...current];'''),
    ...para('//',
        'Two behaviours fall out of this. New entries go to the front '
        'of the list, so the drawer is newest-first without ever '
        'sorting by savedAt. And saving is not idempotent: pressing '
        '“Save to Notebook” twice creates two entries. There is no '
        'deduplication. For a tool with a refine step that is arguably '
        'a feature, since the original and the refined topic can both '
        'be kept as snapshots, but that is an inference; the code does '
        'not say it is intended.'),

    ...sec('immutability and the one editable field'),
    ...code('dart', 'lib/models/notebook_entry.dart · copyWith', r'''
  NotebookEntry copyWith({String? personalNotes}) {
    return NotebookEntry(
      id: id,
      topic: topic,
      personalNotes: personalNotes ?? this.personalNotes,
      savedAt: savedAt,
    );
  }'''),
    ...para('//',
        'copyWith offers exactly one knob. A saved topic cannot be '
        'edited, only annotated: the type system says what the product '
        'says. If the student wants a different topic they refine and '
        'save again. NotebookController.updateNotes uses this to '
        'rewrite one entry in the list, and the drawer calls it from '
        'the notes field’s onChanged, so every keystroke produces a '
        'new entry value, a new list, and a full re-serialization of '
        'the notebook to storage. There is no debounce.'),

    ...sec('serialization: strict where it must be, forgiving where it can'),
    ...code('dart', 'lib/models/notebook_entry.dart · fromJson', r'''
  factory NotebookEntry.fromJson(Map<String, dynamic> json) {
    return NotebookEntry(
      id: json['id']?.toString() ?? '',
      topic: NarrowTopic.fromJson(json['topic'] as Map<String, dynamic>),
      personalNotes: json['personalNotes']?.toString() ?? '',
      savedAt:
          DateTime.tryParse(json['savedAt']?.toString() ?? '') ??
          DateTime.now(),
    );
  }'''),
    ...para('//',
        'The asymmetry is deliberate-looking. A missing id, missing '
        'notes or an unparseable date each degrade to a default, and '
        'DateTime.tryParse returns null rather than throwing. A '
        'missing or non-object topic throws, because an entry without '
        'a topic has no reason to exist. The throw lands in '
        'NotebookController.build, which is an AsyncNotifier, so the '
        'drawer’s notebookAsync.when(error: ...) branch shows the '
        'generic error text instead of the list. One corrupt entry '
        'therefore hides the whole notebook; the code has no per-entry '
        'recovery.'),
    ...para('//',
        'The date round-trips as ISO 8601 text (toIso8601String in '
        'toJson). Note the fallback in fromJson, DateTime.now(): an '
        'entry with a damaged date silently becomes “saved just now”, '
        'which is wrong but harmless since the date is not shown.'),

    ...sec('where the data lives'),
    ...para('//',
        'The provider serializes the whole list with jsonEncode and '
        'writes it as one string value through shared_preferences. '
        'That package, on the web, is backed by the browser’s local '
        'storage; I am stating that from the package’s documented '
        'behaviour rather than from this repository. If that is right '
        'it is the one place where this app persists anything across '
        'browser sessions, in contrast to the API key, which the '
        'README promises is never written to localStorage. The model '
        'file itself knows nothing about storage; it only offers '
        'toJson and fromJson.'),

    ...sec('what is tested'),
    ...para('//',
        'Nothing in test/ touches NotebookEntry or the notebook '
        'provider. The round trip works, if it works, by the '
        'inheritance of NarrowTopic.toJson and fromJson, which the '
        'client tests exercise on the parsing side only.'),

    ...sec('limits and what is next'),
    ...pt('//', 'one bad entry hides all',
        'wrapping each entry’s parse in a try would drop only the '
        'broken one.'),
    ...pt('//', 'no migration',
        'the key has a v1 suffix and no migration path.'),
    ...pt('//', 'savedAt unused',
        'a date label or a sort-by-date would give the field a job.'),
    ...pt('//', 'no language stored',
        'the entry does not record the language the topic was written '
        'in, so the drawer cannot label or filter by it.'),
    blank,
    link('→ github.com/XNash/xyno-scholar', 'https://github.com/XNash/xyno-scholar'),
  ],
);
