import '../../../models/project.dart';
import '../../authoring.dart';

final Buffer page = makePage(
  'xyno-arch/.gitignore',
  lines: [
    cm('#', '──────────────────────────────────────────'),
    cm('#', '.gitignore — six lines that mark who owns which file'),
    cm('#', 'hand-written here, generated by noctalia, or a backup'),
    cm('#', '──────────────────────────────────────────'),
    blank,
    kv('role', 'keeps noctalia’s generated output and installer backups out of git'),
    kv('language', 'gitignore patterns'),
    kv('size', '6 lines, 153 bytes'),
    kv('history', 'one commit, d552dfd (2026-09-19), never edited since'),
    kv('verified', 'every pattern checked with git check-ignore -v'),

    ...sec('the whole file'),
    ...code('text', '.gitignore', r'''
# Written by noctalia's theme templates, not by hand
home/.config/hypr/noctalia.lua
home/.config/noctalia/settings.toml
home/.config/yazi/
*.bak
*.bak-*'''),
    ...para(
        '#',
        r'The file is a boundary line between two kinds of content. '
        r'On one side is what the owner writes and wants to keep. '
        r'On the other is what a program writes on its own, which '
        r'would turn every theme change into a noisy diff and make '
        r'the repo fight the shell that owns the file. The header '
        r'comment states the rule once. The last two patterns are '
        r'a different thing, the debris of the installer, and the '
        r'two groups are worth taking apart.'),

    ...sec('the generated side: three paths and a directory'),
    ...para(
        '#',
        r'The hand-written noctalia config says which programs '
        r'receive the palette. Two lists name them:'),
    ...code('toml', 'home/.config/noctalia/config.toml · the template lists', r'''
builtin_ids = [ "hyprland", "ghostty", "gtk3", "gtk4" ]
enable_community_templates = true
# yazi is the file manager here; keep it on the same palette as everything else.
community_ids = [ "yazi" ]'''),
    ...para(
        '#',
        r'The first three ignore lines are the outputs of that '
        r'machinery, or of noctalia’s own state, and each one has a '
        r'slightly different story.'),
    blank,
    ...pt(
        '#',
        'home/.config/hypr/noctalia.lua',
        r'the output of the “hyprland” template, and the one file '
        r'here that the hand-written config cannot live without. '
        r'The first lines and the last line of hyprland.lua show '
        r'the dependency:'),
    ...code('lua', 'home/.config/hypr/hyprland.lua · the dependency', r'''
-- Lua config. hyprlang (.conf) is deprecated as of Hyprland 0.55.
-- Colours come from noctalia.lua, regenerated on every theme change.
...
require("noctalia").apply_theme()'''),
    ...para(
        '#',
        r'So a Lua module that is loaded by name is deliberately '
        r'absent from the repository. Colours therefore exist only '
        r'after noctalia has run once and written the module. '
        r'noctalia itself is started by the very config that needs '
        r'its output (hl.exec_cmd("noctalia") in the autostart '
        r'hook), so on a truly fresh machine the first login '
        r'reaches the require before the file exists. I did not '
        r'boot this to find out what Hyprland does then; the '
        r'require is the last line of the file, so everything above '
        r'it, binds and rules included, would already have been '
        r'applied. That ordering is the only reason I would expect '
        r'the failure to be cosmetic, and it is an expectation, '
        r'not a test.'),
    blank,
    ...pt(
        '#',
        'home/.config/noctalia/settings.toml',
        r'the state file the shell writes when settings are changed '
        r'in its GUI. Here the repo disagrees with itself about '
        r'where that file lives. The tracked config opens with:'),
    ...code('toml', 'home/.config/noctalia/config.toml · where the state lives', r'''
# Omarchy Quattro-inspired look, translated to noctalia + niri.
# Hand-written layer. GUI changes land in ~/.local/state/noctalia/settings.toml
# and override anything here.'''),
    ...para(
        '#',
        r'That names ~/.local/state, while the ignore line names a '
        r'path under home/.config. Another script in this repo '
        r'confirms the state directory: notification-focus reads '
        r'noctalia’s notification history from '
        r'${XDG_STATE_HOME:-$HOME/.local/state}/noctalia/. Since '
        r'the installer links files and never directories, a '
        r'settings.toml written to ~/.local/state could never enter '
        r'the checkout anyway. Either the ignore line is a '
        r'leftover from an earlier layout, or it covers a location '
        r'noctalia used to write to. The line is harmless in both '
        r'cases, and I cannot tell which from the history, because '
        r'the file never changed.'),
    blank,
    ...pt(
        '#',
        'home/.config/yazi/',
        r'the trailing slash makes it directory-only, and the '
        r'pattern ignores everything below it. The “yazi” community '
        r'template writes its theme there. The consequence is a '
        r'fact worth knowing: no Yazi configuration is tracked at '
        r'all (git ls-files shows nothing under home/.config/yazi), '
        r'so Yazi runs on defaults plus the generated theme. If a '
        r'keymap.toml or yazi.toml were ever added under that '
        r'directory, git would ignore it silently until this line '
        r'were narrowed to the one theme file.'),

    ...sec('the debris side: *.bak and *.bak-*'),
    ...para(
        '#',
        r'The last two patterns are the installer’s signature. It '
        r'renames anything it would overwrite to <name>.bak-<stamp> '
        r'(install.sh, backup()), where the stamp comes from '
        r'date +%Y%m%d%H%M%S. So *.bak-* matches those names '
        r'exactly. *.bak is the older, more general convention of '
        r'editors and hand copies.'),
    blank,
    ...para(
        '#',
        r'The backups are made beside the destination in $HOME, not '
        r'in the checkout, so they only land inside the repo if '
        r'the destination itself lives inside it. That can happen '
        r'when a whole config directory is symlinked into the '
        r'checkout instead of being linked file by file, which is '
        r'the situation before an installer like this one exists. '
        r'I take the two patterns as cheap insurance and not as '
        r'something the current workflow needs; the repo does not '
        r'say.'),
    blank,
    ...para(
        '#',
        r'Matching was checked, not assumed. git check-ignore -v '
        r'reported the right source line for each of: '
        r'home/.config/hypr/noctalia.lua (line 2), '
        r'home/.config/noctalia/settings.toml (line 3), '
        r'home/.config/yazi/theme.toml (line 4), a file named '
        r'foo.bak (line 5) and one named x/y.bak-2026 (line 6). '
        r'Note the anchoring: the three paths contain a slash in '
        r'the middle, so they are anchored to the directory of '
        r'the .gitignore, while *.bak has no slash and matches at '
        r'any depth.'),

    ...sec('what is not ignored, and what that says'),
    ...para(
        '#',
        r'Reading the list backwards is as informative as reading '
        r'it forwards. Three generated or semi-generated things '
        r'are deliberately tracked.'),
    blank,
    ...pt(
        '#',
        'ghostty/themes/noctalia',
        r'this is noctalia’s generated Ghostty palette, 22 lines of '
        r'Tokyo Night values, and the hand-written file says so in '
        r'its first line:'),
    ...code('ini', 'home/.config/ghostty/config.ghostty · the generated theme', r'''
# Palette is regenerated by noctalia's ghostty template on every theme change.
theme = noctalia'''),
    ...para(
        '#',
        r'It is tracked even though it is regenerated. The '
        r'commit that tightened the repo, 208de62, gives the '
        r'principle behind it: move things out of noctalia’s state '
        r'and into the tracked config “so a fresh machine comes up '
        r'identical instead of falling back to defaults”. A '
        r'snapshot of the palette means the first Ghostty window on '
        r'a new machine is already Tokyo Night. That is my reading '
        r'of the intent, and it explains this file.'),
    blank,
    ...para(
        '#',
        r'The same reasoning, applied to noctalia.lua, points the '
        r'other way: it is also needed on the first run and is '
        r'ignored. The repo contains both decisions without '
        r'reconciling them. A reasonable tidy-up would be to track '
        r'a seed copy of noctalia.lua too, or to document that '
        r'the first Hyprland login is expected to complain once.'),
    blank,
    ...pt(
        '#',
        'the wallpaper',
        r'wallpapers/starry-night-tokyo.png (1,856,346 bytes) is '
        r'output of tools/generate-wallpaper.py and is tracked on '
        r'purpose. install.sh copies it from the checkout and the '
        r'noctalia config points at the copy, so the image has to '
        r'be present on a new machine. Generation takes about 13 '
        r'seconds, so the cache argument is weak; the stronger '
        r'one is that the repo needs no Python at install time. '
        r'Both are my inference.'),
    ...pt(
        '#',
        'the GTK settings',
        r'gtk-3.0/settings.ini and gtk-4.0/settings.ini are '
        r'hand-written (font, dark preference, the DotClick cursor '
        r'theme) and tracked. Whatever the gtk3 and gtk4 templates '
        r'write (I have not seen it) is nowhere in the repo, and is '
        r'not in the ignore file either, because the installer only '
        r'ever links files that already exist under home/.'),

    ...sec('history: written once, still right'),
    ...para(
        '#',
        r'The file arrived in the initial commit on 2026-09-19 and '
        r'has not been touched in the 21 commits since. That '
        r'includes a commit that added 81 files for a cursor theme '
        r'and one that added a stack of bar widgets. Nothing in '
        r'those changes produced a new kind of generated file, '
        r'which is as good a sign as any that the boundary was '
        r'drawn in the right place. The one thing I would not '
        r'call right is the settings.toml path above.'),

    ...sec('what I would change'),
    ...pt(
        '#',
        'narrow the yazi line',
        r'ignore only home/.config/yazi/theme.toml (or whatever '
        r'the template writes) so a hand-written keymap can be '
        r'tracked later without a surprise.'),
    ...pt(
        '#',
        'settle the settings.toml path',
        r'run noctalia, look at where its state lands, and make '
        r'the ignore file and the config.toml header say the same '
        r'thing.'),
    ...pt(
        '#',
        'decide about noctalia.lua',
        r'either seed it or write the first-login behaviour into '
        r'the README. Right now the build order is correct only '
        r'because Hyprland happens to load the require last.'),
    ...pt(
        '#',
        'cheap additions',
        r'nothing that this repo creates today needs *.log or '
        r'__pycache__ entries: the Python files are scripts run '
        r'directly, not imported, so no bytecode cache appears.'),
    blank,
    link('→ github.com/xynorash/xyno-arch',
        'https://github.com/xynorash/xyno-arch'),
  ],
);
