import '../../../models/project.dart';
import '../../authoring.dart';

final Buffer page = makePage(
  'xyno-arch/home/.config/ghostty/config.ghostty',
  lines: [
    cm('#', '──────────────────────────────────────────'),
    cm('#', 'config.ghostty — a terminal that only decides how it behaves'),
    cm('#', 'colours come from noctalia; this file keeps everything else'),
    cm('#', '──────────────────────────────────────────'),
    blank,
    kv('role', 'user config for the Ghostty terminal'),
    kv('language', 'Ghostty config (key = value)'),
    kv('size',     '17 lines, 1 commit (d552dfd, 2026-09-19), unchanged '
    'since'),
    kv('pairs with', 'ghostty/themes/noctalia (palette), hypr/hyprland.lua'),
    ...sec('why the file is so small'),
    ...para('#',
        'Seventeen lines is not a sign of neglect. A terminal config '
        'tends to grow into a mix of two kinds of setting: how the '
        'terminal behaves (font, padding, cursor) and what it looks '
        'like (a few dozen colour values). Here the second kind is '
        'handed away on the first line, which leaves the hand-written '
        'file with only the first kind. The git log agrees about how '
        'little needed changing: the file was written in the initial '
        'commit on 2026-09-19 and has not been touched in the 19 days '
        'of history since, while the neighbouring noctalia config '
        'changed eleven times.'),
    ...sec('the palette is somebody else’s job'),
    ...code('ini', 'home/.config/ghostty/config.ghostty · the first two lines', r'''
# Palette is regenerated by noctalia's ghostty template on every theme change.
theme = noctalia'''),
    ...para('#',
        'Ghostty looks a theme name up in the themes/ directory '
        'beside its config (the reference says '
        '~/.config/ghostty/themes), so "theme = noctalia" resolves to '
        'the file in this repo at ghostty/themes/noctalia. A theme '
        'file is "simply another Ghostty configuration file", with '
        'one rule that matters here: colours written in the main '
        'config override the theme. This file deliberately sets none, '
        'so nothing can fight the generated palette.'),
    blank,
    ...para('#',
        'The comment names the generator: noctalia’s ghostty '
        'template, enabled by builtin_ids in noctalia/config.toml, '
        're-renders the theme "on every theme change". That split is '
        'the useful design decision. A generated file can be '
        'rewritten wholesale at any time because nothing hand-written '
        'lives in it, and the hand-written file never has to be '
        'regenerated because nothing generated lives in it. Each side '
        'of the line is safe to overwrite or edit without knowing '
        'about the other.'),
    ...sec('type: a small size on purpose'),
    ...code('ini', 'home/.config/ghostty/config.ghostty · font', r'''
font-family = JetBrainsMono Nerd Font Mono
font-size = 7.5'''),
    ...pt('#',
        'font-family',
        'JetBrainsMono Nerd Font Mono. The shell and the GTK settings '
        'name "JetBrainsMono Nerd Font" without "Mono". In the Nerd '
        'Fonts naming the Mono variant constrains every patched icon '
        'glyph to a single cell, which keeps a terminal grid aligned, '
        'while the plain variant allows wider icons. Same typeface, '
        'two spacing rules, chosen per toolkit.'),
    ...pt('#',
        'font-size = 7.5',
        'Ghostty’s reference defines the size in points and allows '
        'fractions ("the nearest integer pixel size will be '
        'selected"). At the usual 96 dpi, which this repo does not '
        'state, 7.5 pt is 10 pixels. It sits with the other sizes in '
        'the repo: GTK’s font is 8 and the bar’s text runs at '
        'font_scale 0.8 on a 1920 by 1080 display pinned to scale 1. '
        'The whole desktop is deliberately dense.'),
    ...sec('padding that matches the rounded windows'),
    ...code('ini', 'home/.config/ghostty/config.ghostty · padding', r'''
# Roomy padding — Omarchy terminals breathe.
window-padding-x = 14
window-padding-y = 14
window-padding-balance = true'''),
    ...para('#',
        'Padding is in points, scaled for the display. 14 on each '
        'axis is generous by terminal standards, and the comment '
        'gives the attitude: "Omarchy terminals breathe". There is '
        'also a practical fit with the compositor. hyprland.lua '
        'rounds windows with rounding = 10, and padding larger than '
        'that keeps glyphs clear of the rounded corners. That link is '
        'an observation, not something the comment claims.'),
    blank,
    ...para('#',
        'window-padding-balance deals with a geometry detail most '
        'people never notice. A window’s pixel size is rarely an '
        'exact multiple of the cell size, so there is a sliver left '
        'over. By default the sliver piles up on the right and '
        'bottom, which makes the text look off-centre. With balance '
        'on, Ghostty spreads it evenly over all four edges, so the '
        'margins come out even on every side.'),
    ...sec('the glass: whose blur is it?'),
    ...code('ini', 'home/.config/ghostty/config.ghostty · opacity and blur', r'''
# Glassy panel, matching the bar's translucency.
background-opacity = 0.92
background-blur = true'''),
    ...para('#',
        'background-opacity = 0.92 makes the window background '
        'translucent. The comment says it matches "the bar’s '
        'translucency", and the bar’s background_opacity is 0.96, so '
        'the two are close rather than equal.'),
    blank,
    ...para('#',
        'The second line deserves scepticism. Ghostty’s reference '
        'says background-blur is supported on macOS and on "some '
        'Linux desktop environments", names KDE Plasma, and then '
        'states that all other Linux desktop environments are "as of '
        'now unsupported" without environment-specific help. Hyprland '
        'is not on that list. The blur that is actually visible '
        'behind a translucent terminal here is most likely the '
        'compositor’s:'),
    ...code('lua', 'home/.config/hypr/hyprland.lua · decoration blur', r'''
        blur = {
            enabled = true,
            size    = 6,
            passes  = 3,
        },'''),
    ...para('#',
        'Hyprland blurs what shows through a translucent window when '
        'decoration blur is on, whatever the client asked for '
        '(general compositor behaviour, not documented in this repo). '
        'So background-opacity does the work and background-blur is '
        'probably a harmless extra. Nothing records a test with the '
        'line removed, which is why this is a reading and not a '
        'finding.'),
    blank,
    ...para('#',
        'One more thing the reference notes, and it matters for the '
        'terminal apps this desktop runs: background-opacity applies '
        'to the window background only. Programs that paint their own '
        'cell backgrounds, it names Neovim and tmux, stay opaque '
        'unless background-opacity-cells is turned on (added in '
        'Ghostty 1.2.0), which this file does not do. The glass shows '
        'in the prompt and empty areas, not behind an editor colour '
        'scheme.'),
    ...sec('cursor and mouse'),
    ...code('ini', 'home/.config/ghostty/config.ghostty · last two lines', r'''
cursor-style = block
mouse-hide-while-typing = true'''),
    ...para('#',
        'cursor-style = block sets the default shape. The reference '
        'warns that shell integration automatically switches the '
        'cursor to a bar at the prompt "regardless of this '
        'configuration". Integration auto-injection defaults to '
        '"detect", this file sets nothing about it, and the repo '
        'tracks a .bashrc, so at the shell prompt the cursor is '
        'probably a bar anyway and the block shows up in programs '
        'that set their own cursor style or none, such as full-screen '
        'editors. That is a reading of the docs, not something '
        'observed. The cursor colours come from the theme: '
        'cursor-color is the foreground and cursor-text is the '
        'background, which makes a block cursor invert the character '
        'under it.'),
    ...para('#',
        'mouse-hide-while-typing = true hides the pointer on a '
        'keystroke and shows it again on movement, which helps when '
        'the pointer is a 32-pixel custom cursor (the theme and size '
        'are set in the GTK settings and in hyprland.lua).'),
    ...sec('how Ghostty is launched: the config styles every TUI'),
    ...para('#',
        'Ghostty is not only the terminal; it is the window that '
        'every text-mode tool in this desktop appears in, so these 17 '
        'lines style all of them. hyprland.lua launches it three '
        'ways:'),
    ...code('lua', 'home/.config/hypr/hyprland.lua · launchers (trimmed)', r'''
hl.bind(mod .. " + T", hl.dsp.exec_cmd("ghostty"))
...
hl.bind(mod .. " + E", hl.dsp.exec_cmd("ghostty -e yazi"))
...
local cheatsheet = "ghostty --class=com.hypr.Keybinds -e /home/xynorash/.config/hypr/keybinds.sh"
hl.bind(mod .. " + SHIFT + slash",    hl.dsp.exec_cmd(cheatsheet))
hl.bind(mod .. " + SHIFT + question", hl.dsp.exec_cmd(cheatsheet))'''),
    ...pt('#',
        'SUPER+T',
        'a plain terminal.'),
    ...pt('#',
        'SUPER+E',
        '"ghostty -e yazi", the file manager. Yazi is also themed by '
        'a noctalia community template, so it matches the terminal it '
        'runs in.'),
    ...pt('#',
        'SUPER+SHIFT+/',
        'the keybinding cheat sheet. --class=com.hypr.Keybinds gives '
        'the window a handle, and a window rule uses it:'),
    ...code('lua', 'home/.config/hypr/hyprland.lua · the cheat-sheet window rule', r'''
hl.window_rule({
    name   = "keybinds-cheatsheet",
    match  = { class = "^(com\\.hypr\\.Keybinds)$" },
    float  = true,
    size   = "900 820",
    center = true,
})'''),
    ...para('#',
        'The class is the trick: a terminal window with a known class '
        'can be floated, sized and centred by Hyprland without any '
        'special support in the terminal. The cheat sheet '
        '(keybinds.sh, which parses hyprland.lua itself) therefore '
        'opens as a 900 by 820 floating panel in the same type, '
        'padding and colours as the terminal beside it.'),
    ...sec('limits and open questions'),
    ...pt('#',
        'who writes config.ghostty?',
        'noctalia’s docs say that disabling a template removes "any '
        'Noctalia-owned include or theme selection that the template '
        'added to the application’s config". The "theme = noctalia" '
        'line and the comment above it read like exactly that sort of '
        'line, and the repo cannot say whether the template wrote '
        'them or the author did.'),
    ...pt('#',
        'symlinks',
        'install.sh symlinks this file into ~/.config/ghostty. '
        'Whether a template writes through a symlink or replaces it '
        'is not recorded anywhere in the repo.'),
    ...pt('#',
        'not set',
        'scrollback, shell-integration features, window decorations, '
        'keybindings: all Ghostty defaults. Not a gap so much as the '
        'absence of a reason to change them.'),
    ...pt('#',
        'the blur line',
        'as above: probably redundant here, untested without it.'),
    ...pt('#',
        'small type',
        '7.5 pt is an acquired taste; there is no per-window override '
        'in the config, only Ghostty’s runtime font-size shortcuts.'),
    blank,
    link('→ github.com/xynorash/xyno-arch', 'https://github.com/xynorash/xyno-arch'),
  ],
);
