import '../../../models/project.dart';
import '../../authoring.dart';

final Buffer page = makePage(
  'xyno-arch/home/.config/ghostty/themes/noctalia',
  lines: [
    cm('#', '──────────────────────────────────────────'),
    cm('#', 'noctalia — a generated terminal palette, kept in git'),
    cm('#', 'Tokyo Night in 22 lines: sixteen ANSI colours, two base colours, cursor, selection'),
    cm('#', '──────────────────────────────────────────'),
    blank,
    kv('role', 'Ghostty theme file, written by a noctalia template'),
    kv('language', 'Ghostty config syntax (no extension)'),
    kv('size', '22 lines, 1 commit (d552dfd, 2026-09-19)'),
    kv('palette', 'Tokyo Night: background 1a1b26, foreground c0caf5'),
    kv('selected by', '"theme = noctalia" in ghostty/config.ghostty'),
    ...sec('what this file is'),
    ...para('#',
        'A Ghostty theme is, in the reference’s words, "simply '
        'another Ghostty configuration file": same syntax, same '
        'options, looked up by name in a themes/ directory next to '
        'the main config. This one is called noctalia because '
        'noctalia writes it. The first line of ghostty/config.ghostty '
        'says the palette "is regenerated by noctalia’s ghostty '
        'template on every theme change", and noctalia/config.toml '
        'turns that template on with builtin_ids = [ "hyprland", '
        '"ghostty", "gtk3", "gtk4" ].'),
    blank,
    ...para('#',
        'It is a generated file with no hand-written lines, and that '
        'is worth saying twice because it is tracked in git. The '
        'sibling output for Hyprland (hypr/noctalia.lua) is listed in '
        '.gitignore as "written by noctalia’s theme templates, not by '
        'hand"; this one is not. The rest of this page is about what '
        '22 lines of colour contain, and about the choice to keep '
        'them.'),
    ...sec('the sixteen ANSI colours'),
    ...code('ini', 'home/.config/ghostty/themes/noctalia · palette 0 to 15', r'''
palette = 0=#15161e
palette = 1=#f7768e
palette = 2=#9ece6a
palette = 3=#e0af68
palette = 4=#7aa2f7
palette = 5=#bb9af7
palette = 6=#7dcfff
palette = 7=#a9b1d6
palette = 8=#414868
palette = 9=#f7768e
palette = 10=#9ece6a
palette = 11=#e0af68
palette = 12=#7aa2f7
palette = 13=#bb9af7
palette = 14=#7dcfff
palette = 15=#c0caf5'''),
    ...para('#',
        'Terminals expose 16 named colours to programs: indices 0 to '
        '7 are black, red, green, yellow, blue, magenta, cyan, white, '
        'and 8 to 15 are their bright counterparts. The mapping is '
        'not guesswork: noctalia’s own terminal-sequences example in '
        'its docs binds terminal_normal_black to index 0 and '
        'terminal_bright_white to 15 in exactly this order. Its token '
        'list for terminal templates has 22 entries, 16 colours plus '
        'foreground, background, cursor, cursor text, selection '
        'foreground and selection background, which is this file’s '
        'line count.'),
    blank,
    ...para('#',
        'Only 0 to 15 are given. The 256-colour cube and grey ramp '
        '(indices 16 to 255) are left to Ghostty. Its reference '
        'explains that palette-generate, which derives them from the '
        'base 16, is off by default (available since 1.3.0) because '
        '"many legacy programs using the 256-color palette hardcode '
        'assumptions" about the xterm values. Nothing here turns it '
        'on, so a program that asks for a 256-colour index will get '
        'the xterm colour, not a Tokyo Night one. Colour-heavy tools '
        'that stick to the 16 named colours match the theme exactly; '
        'those that use the cube do not.'),
    ...sec('the base colours'),
    ...code('ini', 'home/.config/ghostty/themes/noctalia · background, foreground, cursor, selection', r'''
background = #1a1b26
foreground = #c0caf5
cursor-color = #c0caf5
cursor-text = #1a1b26
selection-background = #283457
selection-foreground = #c0caf5'''),
    ...para('#',
        'Foreground is c0caf5 and background is 1a1b26. The cursor '
        'takes the foreground colour and its text takes the '
        'background colour, so the block cursor set in config.ghostty '
        'is a light rectangle with the underlying character knocked '
        'out in the background colour, which keeps it readable. '
        'Selection reverses the idea: a dark blue (283457) behind '
        'light text.'),
    ...sec('an observation: bright colours that are not'),
    ...para('#',
        'Compare indices 1 to 6 with 9 to 14. They are identical: '
        'f7768e, 9ece6a, e0af68, 7aa2f7, bb9af7 and 7dcfff appear '
        'twice each. The bright row differs from the normal row only '
        'at the ends: black (15161e becomes 414868) and white (a9b1d6 '
        'becomes c0caf5). Across all 16 slots there are therefore '
        'only 10 distinct colours.'),
    ...para('#',
        'The practical effect: a tool that relies on "bright red" '
        'looking different from "red", a diff viewer say, gets no '
        'difference from this theme. Whether that is how Tokyo Night '
        'is designed or a simplification in the template is not '
        'recorded in the repo.'),
    ...sec('measured: how readable is each colour'),
    ...para('#',
        'The contrast figures below are not in the repo. They were '
        'computed from the hex values with the WCAG 2.x formula: each '
        'channel is linearised from sRGB, relative luminance is L = '
        '0.2126 R + 0.7152 G + 0.0722 B, and contrast is (L_lighter + '
        '0.05) / (L_darker + 0.05). All are against the background '
        '1a1b26.'),
    ...pt('#',
        'foreground c0caf5',
        '10.59 to 1. Bright white (15) is the same colour.'),
    ...pt('#',
        'the six hues',
        'red 6.46, blue 6.79, magenta 7.39, yellow 8.55, green 9.35, '
        'cyan 9.96. All clear the 4.5 to 1 that WCAG sets for body '
        'text.'),
    ...pt('#',
        'white a9b1d6 (7)',
        '8.10 to 1.'),
    ...pt('#',
        'selection',
        'foreground on 283457 is 7.57 to 1.'),
    ...pt('#',
        'bright black 414868 (8)',
        '1.91 to 1. Many command-line tools use this slot for '
        'secondary text: suggestions, comments, dim prompts. At 1.91 '
        'it is below even the 3 to 1 WCAG asks of large text. Quiet '
        'by design, and hard to read on a weak display.'),
    ...pt('#',
        'black 15161e (0)',
        '1.05 to 1, nearly the background itself. It is meant as a '
        'fill colour, for example behind a status segment, not for '
        'text. A program that prints black text without setting a '
        'background would be invisible.'),
    ...para('#',
        'The shape of the table is the lesson: a palette can be '
        'beautiful and still have two slots that are deliberately not '
        'for reading. Knowing which two is what lets you configure '
        'tools (a shell’s suggestion colour, a pager’s dim style) '
        'around them.'),
    ...sec('where these hex values come from: one palette, many files'),
    ...para('#',
        'The same sixteen hexes show up elsewhere in the repo, which '
        'is the evidence that the palette is chosen once. The '
        'wallpaper generator hard-codes the background as a gradient '
        'stop and draws its stars from seven of this theme’s colours:'),
    ...code('python', 'tools/generate-wallpaper.py · gradient stop and star colours (trimmed)', r'''
         (0.70, (0x1a, 0x1b, 0x26)),
...
STAR_COLS = ([(0xc0, 0xca, 0xf5)] * 5 + [(0xa9, 0xb1, 0xd6)] * 3 +
             [(0x7a, 0xa2, 0xf7)] * 2 +
             [(0x7d, 0xcf, 0xff), (0xbb, 0x9a, 0xf7), (0xe0, 0xaf, 0x68), (0xf7, 0x76, 0x8e)])'''),
    ...para('#',
        '(0x1a, 0x1b, 0x26) is 1a1b26, the background above. The star '
        'colours are c0caf5, a9b1d6, 7aa2f7, 7dcfff, bb9af7, e0af68 '
        'and f7768e: palette entries 15, 7, 4, 6, 5, 3 and 1. The '
        'script’s docstring states the intent: "Colours are taken '
        'from the Tokyo Night palette so the wallpaper matches the '
        'rest of the desktop." The login screen agrees: '
        'system/etc/greetd/config.toml passes tuigreet '
        '"--matrix-colors" 7dcfff, 7aa2f7 and bb9af7, the cyan, blue '
        'and magenta of this file.'),
    ...sec('why a generated file is tracked'),
    ...para('#',
        'The tracked and ignored lists draw a line. Ignored: '
        'hypr/noctalia.lua, noctalia/settings.toml, and Yazi’s '
        'config. Tracked: this theme. The repo does not state the '
        'reason, so what follows is inference. install.sh symlinks '
        'every file under home/ into the real ~/.config, so a fresh '
        'checkout puts a working theme where Ghostty looks for it '
        'before noctalia has ever run. Without it, "theme = noctalia" '
        'would point at a missing file on the first terminal launch.'),
    ...para('#',
        'There is one thing the repo cannot tell. If noctalia writes '
        'its output by opening the symlink and writing through it, '
        'every palette change lands in the repo’s copy and shows up '
        'in "git diff", which would make the tracked file a record of '
        'the theme. If it instead replaces the symlink with a regular '
        'file, the repo copy is a snapshot that quietly drifts. '
        'History cannot distinguish them: the file has one commit.'),
    ...sec('limits'),
    ...pt('#',
        'dark only',
        'mode is pinned to dark in noctalia/config.toml, and this '
        'file holds one palette. A light mode would need a light/dark '
        'theme pair in config.ghostty, which does not exist.'),
    ...pt('#',
        'no consistency check',
        'nothing verifies that this file, the wallpaper constants and '
        'the greeter colours agree. They do today because they were '
        'set from the same palette.'),
    ...pt('#',
        'contrast figures',
        'derived, not measured on a screen, and they ignore the '
        'terminal window’s translucency (background-opacity 0.92), '
        'which shifts the effective background a little toward '
        'whatever is behind it.'),
    blank,
    link('→ github.com/xynorash/xyno-arch', 'https://github.com/xynorash/xyno-arch'),
  ],
);
