// GENERATED by tools/gen_registry.py — do not edit.
import '../models/project.dart';

/// Every project page, in file order. The explorer tree is built from
/// each page's path, so order here only affects ties.
final List<Buffer> kPageBuffers = [
];
